version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 16
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase
    labels:
      - "deps"
      - "go"
    reviewers:
      - "braccae"
    automerge: true
    automerged_updates:
      - match:
          update_type: "patch"
      - match:
          update_type: "minor"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "github-actions"
    automerge: true
    automerged_updates:
      - match:
          update_type: "patch"
      - match:
          update_type: "minor"

  - package-ecosystem: "docker"
    directory: "container"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): docker"
    labels:
      - "deps"
      - "docker"
    automerge: true
    automerged_updates:
      - match:
          update_type: "patch"
      - match:
          update_type: "minor"
