version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 16
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase
    labels:
      - "deps"
      - "go"
    reviewers:
      - "braccae"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/container"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): docker"
    labels:
      - "deps"
      - "docker"