name: Build and publish container

on:
  release:
    types: [ published, created]
  workflow_run:
    workflows: ["Build and release caddy"]
    types: [completed]
  push:
    branches: [ main ]
    paths:
      - "container/**"
  pull_request:
    paths:
      - "container/**"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Install jq ## on gh runners this isn't needed
      #   if: ${{ github.event_name != 'release' }}
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y jq

      - name: Compute image tag
        id: tag
        shell: bash
        run: |
          set -e
          # Retrieve latest Caddy release semver tag
          BASE=$(curl -sSL -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository_owner }}/caddy/releases/latest" | jq -r .tag_name)
          echo "image_tag=$BASE" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./container
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/riscv64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy:latest
            ghcr.io/${{ github.repository_owner }}/caddy:${{ steps.tag.outputs.image_tag }}
          provenance: false
          build-args: |
            CADDY_VERSION=${{ steps.tag.outputs.image_tag }}
